package otelcolmetadataschema

import "github.com/invopop/jsonschema"

// cf.)
// - https://github.com/open-telemetry/opentelemetry-collector/blob/main/cmd/mdatagen/metadata-schema.yaml
// - https://github.com/open-telemetry/opentelemetry-collector/blob/main/cmd/mdatagen/loader.go

type Metadata struct {
	Type                 string                              `json:"type" jsonschema_description:"The type of the component - Usually the name. The type and class combined uniquely identify the component (eg. receiver/otlp) or subcomponent (eg. receiver/hostmetricsreceiver/cpu)"`
	DeprecatedType       string                              `json:"deprecated_type,omitempty" jsonschema_description:"Optional: A deprecated type that is still available as an alias."`
	DisplayName          string                              `json:"display_name,omitempty" jsonschema_description:"Optional: Human-readable display name for the component."`
	Description          string                              `json:"description,omitempty" jsonschema_description:"Optional: Brief description of the component."`
	Parent               string                              `json:"parent,omitempty" jsonschema_description:"Required for subcomponents: The type of the parent component."`
	ScopeName            string                              `json:"scope_name,omitempty" jsonschema_description:"Optional: Scope name for the telemetry generated by the component."`
	GeneratedPackageName string                              `json:"generated_package_name,omitempty" jsonschema_description:"Optional: The name of the package that mdatagen generates."`
	ReaggregationEnabled bool                                `json:"reaggregation_enabled,omitempty" jsonschema_description:"Optional: Enables per-metric reaggregation config generation for metrics with attributes."`
	Status               *Status                             `json:"status,omitempty" jsonschema_description:"Required for components (Optional for subcomponents): A high-level view of the development status and use of this component"`
	SemConvVersion       string                              `json:"sem_conv_version,omitempty" jsonschema_description:"OTel Semantic Conventions version that will be associated with the scraped metrics. This attribute should be set for metrics compliant with OTel Semantic Conventions."`
	Config               *Config                             `json:"config,omitempty" jsonschema_description:"JSON Schema based definition for the component's configuration structure"`
	ResourceAttributes   map[AttributeName]ResourceAttribute `json:"resource_attributes,omitempty" jsonschema_description:"map of resource attribute definitions with the key being the attribute name."`
	Entities             []Entity                            `json:"entities,omitempty" jsonschema_description:"Optional: array of entity definitions."`
	Attributes           map[AttributeName]Attribute         `json:"attributes,omitempty" jsonschema_description:"map of attribute definitions with the key being the attribute name and value being described below."`
	Metrics              map[MetricName]Metric               `json:"metrics,omitempty" jsonschema_description:"map of metric names with the key being the metric name and valuem being described below."`
	Telemetry            map[MetricName]Metric               `json:"telemetry,omitempty" jsonschema_description:"map of metric names with the key being the metric name and valuem being described below."`
	Events               map[EventName]Event                 `json:"events,omitempty" jsonschema_description:"map of event names with the key being the event name and value being described below."`
	FeatureGates         []FeatureGate                       `json:"feature_gates,omitempty" jsonschema_description:"Optional: list of feature gate definitions."`
	Tests                Tests                               `json:"tests,omitempty" jsonschema_description:"Lifecycle tests generated for this component."`
}

type Status struct {
	Stability            Stability            `json:"stability" jsonschema_description:"The stability of the component - See https://github.com/open-telemetry/opentelemetry-collector#stability-levels"`
	Distributions        []string             `json:"distributions,omitempty" jsonschema_description:"The distributions that this component is bundled with (For example core or contrib). See statusdata.go for a list of common distros."`
	Class                string               `json:"class" jsonschema:"enum=receiver,enum=processor,enum=exporter,enum=connector,enum=extension,enum=cmd,enum=pkg,enum=scraper,enum=converter,enum=provider" jsonschema_description:"The class of the component (For example receiver)"`
	Warnings             []string             `json:"warnings,omitempty" jsonschema_description:"A list of warnings that should be brought to the attention of users looking to use this component"`
	Codeowners           *Codeowners          `json:"codeowners,omitempty" jsonschema_description:"Metadata related to codeowners of the component"`
	UnsupportedPlatforms []string             `json:"unsupported_platforms,omitempty" jsonschema:"items_enum=linux,items_enum=windows"`
	Deprecation          map[string]Component `json:"deprecation,omitempty" jsonschema_description:"The deprecation information for deprecated components."`
}

type Component struct {
	Date      string `json:"date"`
	Migration string `json:"migration"`
}

type Config struct {
	Description string                      `json:"description,omitempty" jsonschema_description:"Description of the configuration schema."`
	Comment     string                      `json:"$comment,omitempty" jsonschema_description:"Additional comments for developers (not included in JSON output)."`
	Type        TypeItem                    `json:"type,omitempty" jsonschema_description:"The type of the configuration object. Typically \"object\" for component configs." jsonschema:"enum=string,enum=number,enum=integer,enum=boolean,enum=object,enum=array,enum=null"`
	Properties  map[PropertyName]Property   `json:"properties,omitempty" jsonschema_description:"Map of configuration properties that define the component's configuration fields."`
	Required    []string                    `json:"required,omitempty" jsonschema_description:"List of required property names. Properties in this list must be present in the config."`
	Defs        map[DefinitionName]Property `json:"$defs,omitempty" jsonschema_description:"Reusable schema definitions that can be referenced via $ref."`
}

type TypeItem string

type PropertyName string
type DefinitionName string

type EntityRef struct {
	Ref string `json:"ref"`
}

type Relationship struct {
	Type   string `json:"type"`
	Target string `json:"target"`
}

type Entity struct {
	Type          string         `json:"type"`
	Brief         string         `json:"brief"`
	Stability     string         `json:"stability,omitempty" jsonschema:"enum=development,enum=alpha,enum=beta,enum=release_candidate,enum=stable"`
	Identity      []EntityRef    `json:"identity"`
	Description   []EntityRef    `json:"description,omitempty"`
	Relationships []Relationship `json:"relationships,omitempty"`
}

type Stability struct {
	Development  []StabilityItem `json:"development,omitempty"`
	Alpha        []StabilityItem `json:"alpha,omitempty"`
	Beta         []StabilityItem `json:"beta,omitempty"`
	Stable       []StabilityItem `json:"stable,omitempty"`
	Deprecated   []StabilityItem `json:"deprecated,omitempty"`
	Unmaintained []StabilityItem `json:"unmaintained,omitempty"`
}

type StabilityItem string

func (StabilityItem) JSONSchema() *jsonschema.Schema {
	return &jsonschema.Schema{
		Type: "string",
		Enum: []any{
			"metrics", "traces", "logs", "traces_to_metrics",
			"metrics_to_metrics", "logs_to_metrics", "extension", "converter", "provider",
		},
	}
}

type Codeowners struct {
	Active   []string `json:"active,omitempty"`
	Emeritus []string `json:"emeritus,omitempty"`
}

type AttributeName string

type EventName string

type Event struct {
	Enabled               bool            `json:"enabled" jsonschema_description:"whether the event is collected by default."`
	Warnings              Warnings        `json:"warnings,omitempty" jsonschema_description:"warnings that will be shown to user under specified conditions."`
	Description           string          `json:"description" jsonschema_description:"event description."`
	ExtendedDocumentation string          `json:"extended_documentation,omitempty" jsonschema_description:"extended documentation of the event."`
	Attributes            []AttributeName `json:"attributes,omitempty" jsonschema_description:"array of attributes that were defined in the attributes section that are emitted by this event."`
	Entity                string          `json:"entity,omitempty" jsonschema_description:"the entity type this event is associated with."`
}

type ResourceAttribute struct {
	Description string   `json:"description" jsonschema_description:"description of the attribute."`
	Enabled     bool     `json:"enabled" jsonschema_description:"whether the resource attribute is added the emitted metrics by default."`
	Enum        []string `json:"enum,omitempty" jsonschema_description:"array of attribute values if they are static values (currently, only string type is supported)."`
	Type        string   `json:"type" jsonschema:"enum=string,enum=int,enum=double,enum=bool,enum=bytes,enum=slice,enum=map" jsonschema_description:"attribute value type."`
	// FullName     attributeName   `json:"-"`
	Warnings Warnings `json:"warnings,omitempty" jsonschema_description:"warnings that will be shown to user under specified conditions."`
}

type Attribute struct {
	Description      string   `json:"description" jsonschema_description:"description of the attribute."`
	NameOverride     string   `json:"name_override,omitempty" jsonschema_description:"this field can be used to override the actual attribute name defined by the key. It should be used if multiple metrics have different attributes with the same name."`
	Enum             []string `json:"enum,omitempty" jsonschema_description:" array of attribute values if they are static values (currently, only string type is supported)."`
	Type             string   `json:"type" jsonschema:"enum=string,enum=int,enum=double,enum=bool,enum=bytes,enum=slice,enum=map" jsonschema_description:"attribute value type."`
	RequirementLevel string   `json:"requirement_level,omitempty" jsonschema:"enum=required,enum=conditionally_required,enum=recommended,enum=opt_in" jsonschema_description:"Optional: indicates requirement level of the attribute."`
	// FullName     attributeName   `json:"-"`
}

type FilterConfig struct {
	Strict string `json:"strict,omitempty" jsonschema:"oneof_required=filter"`
	Regex  string `json:"regexp,omitempty" jsonschema:"oneof_required=filter"`
}

type Property struct {
	AdditionalProperties AdditionalPropertyItem `json:"additionalProperties,omitempty" jsonschema:"enum=bool,enum=object"`
	Const                any                    `json:"const,omitempty"`
	Default              any                    `json:"default,omitempty"`
	Description          string                 `json:"description,omitempty" jsonschema_description:"Description of this configuration property."`
	Deprecated           bool                   `json:"deprecated,omitempty" jsonschema_description:"Indicates if this property is deprecated."`
	Enum                 []string               `json:"enum,omitempty" jsonschema_description:"For string types - allowed values."`
	ExclusiveMinimum     *float64               `json:"exclusiveMinimum,omitempty" jsonschema_description:"For number/integer types - exclusive minimum value."`
	ExclusiveMaximum     *float64               `json:"exclusiveMaximum,omitempty" jsonschema_description:"For number/integer types - exclusive maximum value."`
	Examples             []any                  `json:"examples,omitempty" jsonschema_description:"Example values for this property."`
	Format               string                 `json:"format,omitempty" jsonschema_description:"For string types - format specification (e.g., 'uri', 'email', 'date-time', 'duration')."`
	MaxLength            *int                   `json:"maxLength,omitempty" jsonschema_description:"For string types - maximum length."`
	Maximum              *float64               `json:"maximum,omitempty" jsonschema_description:"For number/integer types - maximum value (inclusive)."`
	MinLength            *int                   `json:"minLength,omitempty" jsonschema_description:"For string types - minimum length."`
	Minimum              *float64               `json:"minimum,omitempty" jsonschema_description:"For number/integer types - minimum value (inclusive)."`
	MultipleOf           *float64               `json:"multipleOf,omitempty" jsonschema_description:"For number types - value must be a multiple of this number."`
	Pattern              string                 `json:"pattern,omitempty" jsonschema_description:"For string types - regular expression pattern that the value must match."`
	Properties           map[string]Property    `json:"properties,omitempty" jsonschema_description:"For object types - properties of the nested object."`
	Ref                  string                 `json:"$ref,omitempty" jsonschema_description:"Reference to another schema definition."`
	Type                 TypeItem               `json:"type,omitempty" jsonschema:"enum=string,enum=number,enum=integer,enum=boolean,enum=object,enum=array,enum=null" jsonschema_description:"The JSON Schema type of this property."`
	MinProperties        *int                   `json:"minProperties,omitempty" jsonschema_description:"For object types - minimum number of properties required."`
	MaxProperties        *int                   `json:"maxProperties,omitempty" jsonschema_description:"For object types - maximum number of properties allowed."`
	Items                *Property              `json:"items,omitempty" jsonschema_description:"For array types - schema for array items."`
	UniqueItems          *bool                  `json:"uniqueItems,omitempty" jsonschema_description:"For array types - whether all items must be unique."`
	AllOf                []Property             `json:"allOf,omitempty" jsonschema_description:"All of these schemas must be satisfied (schema composition)."`
	XCustomType          string                 `json:"x-customType,omitempty"`
	XPointer             bool                   `json:"x-pointer,omitempty"`
	XOptional            bool                   `json:"x-optional,omitempty"`
	MinItems             *int                   `json:"minItems,omitempty" jsonschema_description:"For array types - minimum number of items"`
	MaxItems             *int                   `json:"maxItems,omitempty" jsonschema_description:"For array types - maximum number of items"`
}

type AdditionalPropertyItem string

type MetricName string

type Metric struct {
	Enabled               bool                `json:"enabled" jsonschema_description:"whether the metric is collected by default."`
	Warnings              Warnings            `json:"warnings,omitempty" jsonschema_description:"warnings that will be shown to user under specified conditions."`
	Description           string              `json:"description" jsonschema_description:"metric description."`
	ExtendedDocumentation string              `json:"extended_documentation,omitempty" jsonschema_description:"extended documentation of the metric."`
	Unit                  *string             `json:"unit" jsonschema:"oneof_type=string;number" jsonschema_description:"metric unit as defined by https://ucum.org/ucum.html."`
	Sum                   *Sum                `json:"sum,omitempty" jsonschema:"oneof_required:metrictype" jsonschema_description:"metric type with its settings."`
	Gauge                 *Gauge              `json:"gauge,omitempty" jsonschema:"oneof_required:metrictype" jsonschema_description:"metric type with its settings."`
	Attributes            []AttributeName     `json:"attributes,omitempty" jsonschema_description:"array of attributes that were defined in the attributes section that are emitted by this metric."`
	Entity                string              `json:"entity,omitempty" jsonschema_description:"the entity type this metric is associated with."`
	Stability             string              `json:"stability,omitempty" jsonschema:"enum=development,enum=alpha,enum=beta,enum=stable,enum=deprecated" jsonschema_description:"Optional: the stability level of the metric."`
	Deprecated            *MetricDeprecated   `json:"deprecated,omitempty" jsonschema_description:"Deprecation information for the metric. Required when stability is deprecated."`
	SemanticConvention    *SemanticConvention `json:"semantic_convention,omitempty" jsonschema_description:"Optional: the reference to a semantic convention."`
}

type MetricDeprecated struct {
	Since string `json:"since" jsonschema_description:"Required: version when the metric was deprecated."`
	Note  string `json:"note" jsonschema_description:"Required: migration note."`
}

type SemanticConvention struct {
	Ref string `json:"ref" jsonschema_description:"The semantic convention reference."`
}

type FeatureGate struct {
	ID           string `json:"id" jsonschema_description:"Required: unique identifier for the feature gate."`
	Description  string `json:"description" jsonschema_description:"Required: description of the feature gate."`
	Stage        string `json:"stage" jsonschema:"enum=alpha,enum=beta,enum=stable,enum=deprecated" jsonschema_description:"Required: lifecycle stage of the feature gate."`
	FromVersion  string `json:"from_version" jsonschema_description:"Required: version when the feature gate was introduced."`
	ToVersion    string `json:"to_version,omitempty" jsonschema_description:"Required for stable/deprecated gates: version when the feature gate reached stable stage."`
	ReferenceURL string `json:"reference_url" jsonschema_description:"Required: URL with contextual information about the feature gate."`
}

type Sum struct {
	AggregationTemporality string `json:"aggregation_temporality" jsonschema_description:"whether reported values incorporate previous measurements (cumulative) or not (delta)."`
	Mono                   bool   `json:"monotonic" jsonschema_description:"whether the metric is monotonic (no negative delta values)."`
	MetricValueType        string `json:"value_type" jsonschema_description:"type of number data point values."`
	MetricInputType        string `json:"input_type,omitempty" jsonschema_description:"Indicates the type the metric needs to be parsed from. If set, the generated functions will parse the value from string to value_type."`
}

type Gauge struct {
	MetricValueType string `json:"value_type" jsonschema_description:"type of number data point values."`
	MetricInputType string `json:"input_type,omitempty" jsonschema_description:"Indicates the type the metric needs to be parsed from. If set, the generated functions will parse the value from string to value_type."`
}

type Warnings struct {
	// TODO: each Warnings should have different tags for descriptions

	IfEnabled       string `json:"if_enabled,omitempty"`
	IfEnabledNotSet string `json:"if_enabled_not_set,omitempty"`
	IfConfigured    string `json:"if_configured,omitempty"`
}

type Tests struct {
	Config              any    `json:"config,omitempty" jsonschema_description:"{} by default, specific testing configuration for lifecycle tests."`
	SkipLifecycle       bool   `json:"skip_lifecycle,omitempty" jsonschema_description:"false by default Skip lifecycle tests for this component. Not recommended for components that are not in development."`
	SkipShutdown        bool   `json:"skip_shutdown,omitempty" jsonschema_description:"false by default Skip shutdown tests for this component. Not recommended for components that are not in development."`
	GoLeak              GoLeak `json:"goleak,omitempty" jsonschema_description:"{} by default generates a package_test to enable check for leaks"`
	ExpectConsumerError bool   `json:"expect_consumer_error,omitempty" jsonschema_description:"Whether it's expected that the Consume[Logs|Metrics|Traces] method will return an error with the given configuration."`
}

type GoLeak struct {
	Skip     bool   `json:"skip" jsonschema_description:"set to true if goleak tests should be skipped"`
	Ignore   Ignore `json:"ignore,omitempty"`
	Setup    string `json:"setup,omitempty" jsonschema_description:"upports configuring a setup function that runs before goleak checks"`
	Teardown string `json:"teardown,omitempty" jsonschema_description:"supports configuring a teardown function that runs before goleak checks"`
}

type Ignore struct {
	Top []string `json:"top,omitempty" jsonschema_description:"array of strings representing functions that should be ignore via IgnoreTopFunction"`
	Any []string `json:"any,omitempty" jsonschema_description:"array of strings representing functions that should be ignore via IgnoreAnyFunction"`
}
